# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: ls -la
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: |
      echo Pushing...
      git config --global user.email "nsucheninov@viacode.com"
      git config --global user.name "Nikolai"
      git remote add test1 https://$(GitHubPAT2)@github.com/nsucheninov/test01.git
      git push -f test1 HEAD:master
