# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'SNS GitHub'
    repositoryName: 'nsucheninov/Azure'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tagSource: 'Git tag'
    tag: '1.0'
    assetUploadMode: 'replace'
